---
driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.3
    driver_config:
      run_command: /sbin/init
    
suites:
  - name: haproxy
    driver:
      run_options: --network=testnet --ip=10.1.1.3
      forward: 5050:5050
    run_list:
      - recipe[haproxy::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: apache
    driver:
      run_options: --network=testnet --ip=10.1.1.5
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

